import os
import openai

def generate_instructions(script, openai_key, engine="davinci", max_tokens=150):
  """

  Creates a list of instructions based on a video script using the GPT-3 model of OpenAI.
  
  Args:
    script:
      String containing the video script.
    openai_key:
      Secret API Key. 
    engine:
      The name of the GPT-3 engine. (Default: "davinci")
    max_tokens:
      The maximum number of tokens to be generated. (Default: 150)
  
  Returns:
    response: 
      String containing the list of instructions generated by GPT-3.

  """
  prompt ="###\n"\
  "Text to extract instructions from:\n"\
  "\n"\
  "Hello, today I want to show you how you can configure a template button the notion. So first I created an empty page, give it a title of test page. Then we want to search for the templates button. If we have it and selected now we can configure our own template button. First we will give it a name, we'll name it add a new to do block. And then every block we want to have a header and the to do list. So we're This is the block that actually appears when we are pressing a button. So first we want header. We'll select all section header, name it's pool, block number, and then we could select the number and then we will add a to do list. Then we click on Close. So now every time we click on this add new to do block the new heading the new to do list will appear. This is how template buttons work. If we want to we configured which is press the settings and then we could add this we could probably list it for clothes. Every time we press on the button. This new block with the toggle editor that will appeal to very much\n"\
  "\n"\
  "\n"\
  "Instructions:\n"\
  "1. Create empty page\n"\
  "2. Search for template button\n"\
  "3. Select and configure template button\n"\
  "4. Give it a name\n"\
  "5. Add new block\n"\
  "6. Click on close\n"\
  "7. For configuration, click on settings\n"\
  "\n"\
  "###\n"\
  "Text to extract instructions from:\n"\
  "\n" + script + "\n"\
  "\n"\
  "\n"\
  "Instructions:\n"\
  "1."

  openai.api_key = openai_key

  response = openai.Completion.create(
    engine=engine,
    prompt = prompt,
    temperature=0.0,
    max_tokens=max_tokens,
    top_p=0.0,
    frequency_penalty=0.0,
    presence_penalty=0.0,
    stop=["###"]
  )["choices"][0]["text"]

  return "1." + response